import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, renameSync, rmdirSync, statSync, unlinkSync, writeFileSync, } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { backgroundTimeoutMs, foregroundTimeoutMs, jobTtlMs, maxRetainedJobBytes, maxRetainedJobs } from "./kiro.js";
export function getJobsDir() {
    if (process.env.KIRO_PLUGIN_JOBS_DIR)
        return process.env.KIRO_PLUGIN_JOBS_DIR;
    const uid = process.getuid?.();
    const suffix = uid === undefined ? (process.env.USERNAME || "user") : String(uid);
    return join(tmpdir(), `kiro-plugin-cc-jobs-${suffix}`);
}
/**
 * Job records hold Kiro's full output, which for a private repository is source
 * code and review commentary. The directory is therefore per-user and 0700 --
 * never the shared, world-readable default that `mkdir` would produce.
 */
export function ensureJobsDir() {
    const dir = getJobsDir();
    mkdirSync(dir, { recursive: true, mode: 0o700 });
    const uid = process.getuid?.();
    // Ownership and mode are only enforced for the directory the plugin picks
    // itself. An operator who points KIRO_PLUGIN_JOBS_DIR at a directory of
    // their own has already made that call, and silently chmod-ing a shared
    // directory out from under them would be worse than honouring it. Records
    // are written 0600 either way.
    if (uid !== undefined && !process.env.KIRO_PLUGIN_JOBS_DIR) {
        // lstat first: statSync would follow a symlink planted in the shared temp
        // path, so the uid check would pass while every record landed elsewhere.
        if (lstatSync(dir).isSymbolicLink()) {
            throw new Error(`jobs directory ${dir} is a symbolic link; refusing to use it`);
        }
        const st = statSync(dir);
        // A pre-created directory in the shared temp path would leak every result.
        if (st.uid !== uid) {
            throw new Error(`jobs directory ${dir} is owned by another user (uid ${st.uid}); refusing to use it`);
        }
        // `mkdir -p` leaves the mode of an existing directory alone.
        if ((st.mode & 0o077) !== 0)
            chmodSync(dir, 0o700);
    }
    migrateLegacyJobsDir(dir);
    return dir;
}
/**
 * Ids are generated by this plugin, but they arrive back from slash-command
 * arguments, so they are a trust boundary: without this, `result ../secret`
 * reads any file the user can.
 */
const JOB_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/;
export function isValidJobId(id) {
    return JOB_ID_RE.test(id) && !id.includes("..");
}
const META_EXT = ".json";
const OUT_EXT = ".out";
const TMP_PREFIX = ".tmp-";
/**
 * The shape genId() produces. Pruning deletes files, so it only ever touches
 * names this plugin could itself have written -- an operator who points
 * KIRO_PLUGIN_JOBS_DIR at a directory of their own must not lose anything in
 * it. `isValidJobId` is far too permissive for that: it accepts "package",
 * which is how a stray package.json came to be deleted.
 */
const GENERATED_ID_RE = /^kiro-[0-9a-z]+-[0-9a-z]+$/;
const TMP_RE = /^\.tmp-(\d+)-\d+\.tmp$/;
function requireId(id) {
    if (!isValidJobId(id))
        throw new Error(`invalid job id: ${id}`);
}
// ensureJobsDir, not getJobsDir: reads have to clear the symlink and ownership
// guards too, or a planted directory is still readable by id.
function metaPath(id) {
    requireId(id);
    return join(ensureJobsDir(), `${id}${META_EXT}`);
}
function outPath(id) {
    requireId(id);
    return join(ensureJobsDir(), `${id}${OUT_EXT}`);
}
let tmpSeq = 0;
function nextTmpSeq() {
    tmpSeq += 1;
    return tmpSeq;
}
/** Write-then-rename, so a reader never observes a half-written file. */
function writeAtomic(target, data) {
    const dir = ensureJobsDir();
    // Matched by TMP_RE, so an abandoned one is recognisably ours to clean up.
    // The counter, not just the path length, is what keeps two writes from the
    // same process apart -- they only happen to be sequential today.
    const tmp = join(dir, `${TMP_PREFIX}${process.pid}-${nextTmpSeq()}.tmp`);
    try {
        writeFileSync(tmp, data, { mode: 0o600 });
        renameSync(tmp, target);
    }
    catch (e) {
        try {
            if (existsSync(tmp))
                unlinkSync(tmp);
        }
        catch { /* best effort */ }
        throw e;
    }
}
export function saveJob(job) {
    writeAtomic(metaPath(job.id), JSON.stringify(job, null, 2));
}
/** Stores a job's transcript and returns its byte length. */
export function saveJobResult(id, text) {
    writeAtomic(outPath(id), text);
    return Buffer.byteLength(text);
}
export function readJobResult(id) {
    if (!isValidJobId(id))
        return null;
    try {
        return readFileSync(outPath(id), "utf-8");
    }
    catch {
        /* no transcript file -- may predate the split */
    }
    // Pre-split records hold the transcript inside the metadata. Without this the
    // commands reported "No result stored." with the body sitting right there.
    try {
        const parsed = JSON.parse(readFileSync(metaPath(id), "utf-8"));
        if (parsed && parsed.id === id && typeof parsed.result === "string")
            return parsed.result;
    }
    catch {
        /* unreadable or not in that shape */
    }
    return null;
}
/**
 * Returns null for anything that is not a readable, well-formed record for
 * `expectedId`. The id has to match the file it came from: saveJob always
 * writes `<id>.json`, so a record naming something else could never be updated
 * through its own id -- it would read as running forever while a second,
 * cancelled record accumulated alongside it.
 */
function readJobFile(path, expectedId) {
    let raw;
    try {
        raw = readFileSync(path, "utf-8");
    }
    catch {
        return null;
    }
    let parsed;
    try {
        parsed = JSON.parse(raw);
    }
    catch {
        return null;
    }
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed))
        return null;
    const job = parsed;
    if (typeof job.id !== "string" || typeof job.kind !== "string" || typeof job.startedAt !== "string")
        return null;
    if (job.id !== expectedId)
        return null;
    if (job.status !== "running" && job.status !== "completed" && job.status !== "failed" && job.status !== "cancelled") {
        return null;
    }
    // startedAt drives both sorting and the launch-window check, so a value that
    // does not parse makes the record unusable rather than merely odd.
    if (!Number.isFinite(Date.parse(job.startedAt)))
        return null;
    // finishedAt decides the TTL sweep: an unparseable value compares NaN, which
    // is false either way, and made the record permanently immune to pruning.
    if (job.finishedAt !== undefined) {
        if (typeof job.finishedAt !== "string" || !Number.isFinite(Date.parse(job.finishedAt)))
            return null;
    }
    // resultBytes is summed against the byte budget. A string would concatenate
    // instead of adding, inflating the accumulator and pruning transcripts that
    // are well inside it.
    if (job.resultBytes !== undefined) {
        if (typeof job.resultBytes !== "number" || !Number.isFinite(job.resultBytes) || job.resultBytes < 0)
            return null;
    }
    if (job.pid !== undefined && (typeof job.pid !== "number" || !Number.isInteger(job.pid)))
        return null;
    if (job.timeoutMs !== undefined) {
        if (typeof job.timeoutMs !== "number" || !Number.isFinite(job.timeoutMs) || job.timeoutMs < 1)
            return null;
    }
    if (job.note !== undefined && typeof job.note !== "string")
        return null;
    return migrateInlineResult(job);
}
/**
 * Records written before the metadata/transcript split carried the whole
 * transcript inline. Left as-is, `status` would parse and re-emit megabytes --
 * exactly the cost the split removed -- and the pruning byte budget would count
 * them as nothing, since it reads resultBytes. The field is dropped here and
 * its size accounted for; readJobResult still finds the body itself.
 */
function migrateInlineResult(job) {
    if (typeof job.result !== "string") {
        if ("result" in job)
            delete job.result;
        return job;
    }
    const bytes = Buffer.byteLength(job.result);
    delete job.result;
    return { ...job, resultBytes: job.resultBytes ?? bytes };
}
export function isPidAlive(pid) {
    if (!Number.isInteger(pid) || pid <= 0)
        return false;
    try {
        process.kill(pid, 0);
        return true;
    }
    catch (e) {
        // EPERM means the process exists but belongs to another user.
        return e.code === "EPERM";
    }
}
/**
 * Best-effort argv for `pid`, or null when it cannot be determined. An empty
 * array means the process is there but has no command line -- a zombie or a
 * kernel thread. Kept as an array rather than a string because the runner has
 * to be recognised by position: its prompt is one of these entries, and a
 * prompt that merely mentions another job's id would otherwise match it.
 */
export function pidArgv(pid) {
    if (!Number.isInteger(pid) || pid <= 0)
        return null;
    try {
        return readFileSync(`/proc/${pid}/cmdline`, "utf-8").split("\0").filter(Boolean);
    }
    catch {
        /* not Linux, or the process is gone */
    }
    try {
        // -ww: BSD and macOS truncate to the terminal width when stdout is not a
        // tty, which would drop the job id and defeat the check below.
        const out = execFileSync("ps", ["-ww", "-o", "args=", "-p", String(pid)], {
            encoding: "utf-8",
            timeout: 5_000,
            // Without this the timeout only sends SIGTERM and then keeps waiting.
            killSignal: "SIGKILL",
            stdio: ["ignore", "pipe", "ignore"],
        }).trim();
        // ps gives one string, so argument boundaries are approximated by
        // whitespace. That is enough here: the two entries this is matched on -- the
        // runner's path and the job id -- are adjacent and contain no spaces.
        return out === "" ? [] : out.split(/\s+/);
    }
    catch {
        return null;
    }
}
/** True when the pid is a zombie: still in the table, but finished. */
function isZombie(pid) {
    try {
        const stat = readFileSync(`/proc/${pid}/stat`, "utf-8");
        // Field 3, after the comm field, which may itself contain spaces.
        const after = stat.slice(stat.lastIndexOf(")") + 1).trim();
        return after.startsWith("Z");
    }
    catch {
        return false;
    }
}
/**
 * Whether this argv is our runner for `jobId`. The runner is invoked as
 * `node <...>/kiro-runner.js <jobId> <timeoutMs> <kiro> chat ... <prompt>`, so
 * the id has to sit immediately after the script. Searching the whole command
 * line for it instead meant a runner whose prompt happened to mention another
 * job's id was taken for that job -- and on a recycled pid that had cancel
 * signalling the wrong process group while reporting the wrong job stopped.
 */
function isRunnerFor(argv, jobId) {
    for (let i = 0; i < argv.length - 1; i++) {
        if (argv[i].endsWith("kiro-runner.js") && argv[i + 1] === jobId)
            return true;
    }
    return false;
}
export function classifyPid(pid, jobId) {
    const argv = pidArgv(pid);
    if (argv === null || argv.length === 0) {
        // An empty command line is not somebody else's process: calling it
        // "foreign" asserted a recycled pid that was never observed. A zombie is
        // still definitively finished, though, and saying so is what lets a killed
        // runner be noticed at once instead of waiting out its budget.
        if (isZombie(pid))
            return "dead";
        return "unknown";
    }
    return isRunnerFor(argv, jobId) ? "ours" : "foreign";
}
/**
 * Longest a single writeAtomic could plausibly be in flight. Past this a
 * temporary is abandoned however alive the pid in its name looks, since pids
 * are recycled and tmpdir survives reboots on some platforms.
 */
const TMP_INFLIGHT_MS = 5 * 60_000;
/** Grace over a run's own budget before an unverifiable runner is called stale. */
const STALE_SLACK_MS = 60_000;
/**
 * How long this job may run before an unverifiable pid is treated as stale. The
 * run's recorded budget when there is one; otherwise the larger of the two
 * configured budgets, since a record written before the field existed gives no
 * clue which mode it was. Taking the background budget alone would call a
 * still-running foreground job stale whenever the foreground budget was set
 * higher -- and a stale record is uncancellable and eligible for pruning, so it
 * would strand kiro-cli and then delete the record out from under it.
 */
function staleAfterMs(job) {
    const budget = job.timeoutMs ?? Math.max(foregroundTimeoutMs(), backgroundTimeoutMs());
    return budget + STALE_SLACK_MS;
}
/** How long a record may claim "running" without ever having recorded a pid. */
const PIDLESS_GRACE_MS = 60_000;
/**
 * A job is marked completed by the detached runner itself. If the runner was
 * killed before it could do that, the record would claim "running" forever, so
 * report the truth on read instead. This is read-side only -- nothing is
 * rewritten, because the runner may still be the one holding the pid.
 */
export function reconcile(job) {
    if (job.status !== "running")
        return job;
    if (job.pid === undefined) {
        // The launcher writes the record before it knows the runner's pid, so there
        // is nothing to check liveness against in that window. A record that never
        // gained a pid means the launcher died in it.
        const age = Date.now() - Date.parse(job.startedAt);
        // Fail closed: an unusable timestamp must not keep a job "running" forever.
        if (Number.isFinite(age) && age <= PIDLESS_GRACE_MS)
            return job;
        // finishedAt is deliberately left as stored -- usually absent. Synthesizing
        // "now" made one stale record look like the most recently finished job on
        // every read, shadowing every genuine result for the whole retention window.
        return {
            ...job,
            status: "failed",
            note: job.note ?? "ERROR: the job was never started (its launcher exited before recording a runner).",
        };
    }
    if (isPidAlive(job.pid)) {
        const verdict = classifyPid(job.pid, job.id);
        const age = Date.now() - Date.parse(job.startedAt);
        // Fail closed on an unusable age, as the pidless guard above does.
        const withinBudget = Number.isFinite(age) && age <= staleAfterMs(job);
        // A supervisor that is alive and verifiably this job's is authoritative,
        // whatever the clock says: the job really is running. Judging it by elapsed
        // wall time instead was worse than the wedged runner it was meant to catch
        // -- a suspend/resume across a long run made the record read "failed" while
        // the runner was still working, cancel then refused to signal it, and
        // pruning deleted the record and transcript out from under it, after which
        // the runner discarded its own output. A verified runner can always be
        // stopped with `cancel`, which is the remedy for one that is stuck; only an
        // unverifiable pid needs a bound, because that is the case cancel refuses.
        if (verdict === "ours")
            return job;
        if (verdict === "dead") {
            return {
                ...job,
                status: "failed",
                note: job.note ?? "ERROR: the Kiro runner exited without recording a result (killed or crashed).",
            };
        }
        if (verdict === "foreign") {
            return {
                ...job,
                status: "failed",
                note: job.note ?? `ERROR: the Kiro runner is gone; pid ${job.pid} now belongs to another process.`,
            };
        }
        if (verdict === "unknown") {
            // Nothing here can be read (no /proc, no ps), so we cannot tell our runner
            // from a process that inherited its pid. Trusting it indefinitely made a
            // dead job "running" for ever: exempt from every retention budget because
            // pruning treats running jobs as live, and refused by cancel because an
            // unproven pid is not signalled. No run can outlive the largest timeout,
            // so past that it is stale whatever the pid now belongs to.
            if (withinBudget)
                return job;
            return {
                ...job,
                status: "failed",
                note: job.note ?? "ERROR: the Kiro runner could not be verified on this platform and has outlived its timeout.",
            };
        }
    }
    // As above: no invented finishedAt.
    return {
        ...job,
        status: "failed",
        note: job.note ?? "ERROR: the Kiro runner exited without recording a result (killed or crashed).",
    };
}
/** The record exactly as stored, with no liveness interpretation applied. */
export function loadJobRaw(id) {
    if (!isValidJobId(id))
        return null;
    return readJobFile(metaPath(id), id);
}
export function loadJob(id) {
    const job = loadJobRaw(id);
    return job ? reconcile(job) : null;
}
export function listJobs() {
    const dir = ensureJobsDir();
    const jobs = [];
    for (const f of readdirSync(dir)) {
        if (!f.endsWith(META_EXT))
            continue;
        const job = readJobFile(join(dir, f), f.slice(0, -META_EXT.length));
        if (job)
            jobs.push(reconcile(job));
    }
    return jobs.sort((a, b) => b.startedAt.localeCompare(a.startedAt));
}
function removeJobFiles(dir, id) {
    for (const ext of [META_EXT, OUT_EXT]) {
        try {
            unlinkSync(join(dir, `${id}${ext}`));
        }
        catch {
            /* already gone, or never written */
        }
    }
}
export function finishedTime(job) {
    const t = Date.parse(job.finishedAt ?? job.startedAt);
    return Number.isFinite(t) ? t : 0;
}
/**
 * A transcript's size. resultBytes is written with the record, so a transcript
 * left behind by a runner that died between the two writes has none -- and
 * charging it zero let arbitrarily large orphans sit inside the byte budget.
 */
function transcriptBytes(dir, job) {
    if (job.resultBytes !== undefined)
        return job.resultBytes;
    try {
        return statSync(join(dir, `${job.id}${OUT_EXT}`)).size;
    }
    catch {
        return 0;
    }
}
function ageOf(dir, name) {
    try {
        return Date.now() - statSync(join(dir, name)).mtimeMs;
    }
    catch {
        return 0;
    }
}
let legacyMigrated = false;
/**
 * The default jobs directory gained a per-user suffix, which left any
 * pre-upgrade store behind at the old shared path -- still holding transcripts,
 * created with the default mode so world-readable, and no longer read by
 * anything. Its records are moved into the current store rather than left to
 * age out: they are the only records that can still hold a transcript inline,
 * and draining them meant the compatibility code for that shape had nothing to
 * read. Only names this plugin could have generated are moved, nothing already
 * present is overwritten, and anything else in the directory is left alone.
 *
 * Runs at most once per process, from ensureJobsDir, so a user who only ever
 * runs `status` still gets the old directory tightened and carried over.
 */
function migrateLegacyJobsDir(target) {
    if (legacyMigrated)
        return;
    legacyMigrated = true;
    if (process.env.KIRO_PLUGIN_JOBS_DIR)
        return;
    const legacy = join(tmpdir(), "kiro-plugin-cc-jobs");
    if (legacy === target)
        return;
    // Not gated on having a uid: a platform without one is exactly the platform
    // whose default path gained a suffix, so skipping it there left the
    // pre-upgrade records invisible and unprunable on the only system that had
    // to migrate. The ownership and mode checks below are what need a uid.
    const uid = process.getuid?.();
    try {
        if (lstatSync(legacy).isSymbolicLink())
            return;
        const st = statSync(legacy);
        if (!st.isDirectory())
            return;
        if (uid !== undefined) {
            if (st.uid !== uid)
                return;
            if ((st.mode & 0o077) !== 0)
                chmodSync(legacy, 0o700);
        }
    }
    catch {
        return; // not there, or not ours to touch
    }
    let names;
    try {
        names = readdirSync(legacy);
    }
    catch {
        return;
    }
    for (const name of names) {
        if (TMP_RE.test(name)) {
            try {
                unlinkSync(join(legacy, name));
            }
            catch { /* best effort */ }
            continue;
        }
        const ext = name.endsWith(META_EXT) ? META_EXT : name.endsWith(OUT_EXT) ? OUT_EXT : null;
        if (ext === null)
            continue;
        if (!GENERATED_ID_RE.test(name.slice(0, -ext.length)))
            continue;
        const to = join(target, name);
        if (existsSync(to))
            continue;
        try {
            renameSync(join(legacy, name), to);
            // rename keeps the old mode, and pre-0.1.0 records were written without
            // one -- so a migrated transcript of private source stayed 0644.
            if (uid !== undefined)
                chmodSync(to, 0o600);
        }
        catch {
            /* leave it where it is */
        }
    }
    try {
        if (readdirSync(legacy).length === 0)
            rmdirSync(legacy);
    }
    catch {
        /* still has files, or gone already */
    }
}
/**
 * Keeps the store bounded. Every run -- foreground included -- leaves a record
 * and a transcript, so without this the directory grows without limit. Three
 * budgets apply to finished jobs: age, count and total transcript bytes. A
 * running job is never touched.
 *
 * The scan is over the directory rather than over listJobs(), so that a record
 * listJobs rejects (corrupt, mismatched id, unusable timestamp), an orphaned
 * transcript and an abandoned temporary file are cleaned up too -- none of them
 * is visible to it. Only names this plugin could have generated are ever
 * removed, and only once past the TTL; everything else in the directory is left
 * strictly alone. Best effort throughout -- housekeeping must not be able to
 * fail a job.
 */
export function pruneJobs() {
    let dir;
    let names;
    try {
        dir = ensureJobsDir();
        names = readdirSync(dir);
    }
    catch {
        return;
    }
    const ttl = jobTtlMs();
    const live = new Set();
    const terminal = [];
    const transcripts = [];
    // Transcripts nothing can read, still inside the age grace. They are held
    // only in case a young unreadable record recovers.
    const strays = [];
    for (const name of names) {
        const tmp = TMP_RE.exec(name);
        if (tmp) {
            // Protected only while it is plausibly a write in progress: the name
            // carries the writer's pid, and removing a live writer's temporary makes
            // its rename fail with ENOENT -- a finished run then reported as never
            // having recorded a result. Liveness alone is not enough, because a
            // recycled pid would protect an abandoned file for ever, so it must also
            // be younger than any single write could take. Anything else is
            // abandoned and goes now, whatever the budget says.
            if (isPidAlive(Number(tmp[1])) && ageOf(dir, name) < TMP_INFLIGHT_MS)
                continue;
            try {
                unlinkSync(join(dir, name));
            }
            catch { /* best effort */ }
            continue;
        }
        if (name.endsWith(OUT_EXT)) {
            const id = name.slice(0, -OUT_EXT.length);
            if (GENERATED_ID_RE.test(id))
                transcripts.push(id);
            continue;
        }
        if (!name.endsWith(META_EXT))
            continue;
        const id = name.slice(0, -META_EXT.length);
        if (!GENERATED_ID_RE.test(id))
            continue;
        const job = readJobFile(join(dir, name), id);
        if (!job) {
            // Ours by name but unreadable by every other code path, so it can only
            // ever take up space.
            if (ageOf(dir, name) > ttl)
                removeJobFiles(dir, id);
            continue;
        }
        if (reconcile(job).status === "running")
            live.add(id);
        else
            terminal.push(job);
    }
    // By finish time, which is how `result` picks the latest run. Ordering by
    // startedAt instead meant that with two overlapping background jobs the caps
    // deleted the one that finished last, and `result` then quietly returned an
    // older transcript.
    terminal.sort((a, b) => finishedTime(b) - finishedTime(a));
    const cutoff = Date.now() - ttl;
    const doomed = new Set();
    for (const job of terminal) {
        if (finishedTime(job) < cutoff)
            doomed.add(job.id);
    }
    // Newest-first, so the tail is what falls outside the count cap.
    for (const job of terminal.slice(maxRetainedJobs()))
        doomed.add(job.id);
    // Then trim by stored bytes: fifty ten-megabyte transcripts are within the
    // count cap and still make the store unusable. Newest-first, keeping each
    // record that still fits and dropping the ones that do not, so `kept` is the
    // size of what actually survives. Accumulating the doomed ones too overstated
    // it, which then made the stray sweep below fire on a store well inside its
    // budget.
    const byteBudget = maxRetainedJobBytes();
    let kept = 0;
    let keptAny = false;
    for (const job of terminal) {
        if (doomed.has(job.id))
            continue;
        // The newest survivor is always retained, however large, and is not charged
        // against the budget -- charging it meant a single oversized transcript
        // exhausted the budget on its own and doomed every older record that would
        // have fitted. The count cap has this floor for free (its minimum is one);
        // without it here, raising KIRO_PLUGIN_MAX_OUTPUT_BYTES above the byte
        // budget meant the next job start deleted the run just finished, before
        // anyone had read it.
        if (!keptAny) {
            keptAny = true;
            continue;
        }
        const bytes = transcriptBytes(dir, job);
        if (kept + bytes > byteBudget) {
            doomed.add(job.id);
            continue;
        }
        kept += bytes;
    }
    for (const id of doomed)
        removeJobFiles(dir, id);
    // A transcript whose record is gone is unreachable. Age-guarded like every
    // other stale-file path, so a young record that merely failed to parse this
    // time does not lose its output.
    const retained = new Set(terminal.filter((j) => !doomed.has(j.id)).map((j) => j.id));
    for (const id of transcripts) {
        if (live.has(id) || retained.has(id) || doomed.has(id))
            continue;
        const name = `${id}${OUT_EXT}`;
        if (ageOf(dir, name) > ttl) {
            try {
                unlinkSync(join(dir, name));
            }
            catch { /* best effort */ }
        }
        else {
            strays.push(name);
        }
    }
    // Whatever survived on age alone is still unreachable, and it was charged
    // nothing: three orphaned transcripts held 600 KB against a 1 KB budget for
    // the full seven days. Nothing can read them, so once the store is over
    // budget they go first, whatever their age. Abandoned temporaries are not in
    // here -- they are removed outright above.
    let strayBytes = 0;
    for (const name of strays) {
        try {
            strayBytes += statSync(join(dir, name)).size;
        }
        catch { /* gone */ }
    }
    // Against the charged bytes only. The newest run is retained unconditionally
    // and not charged, so a single large transcript can put the store over the
    // budget on its own -- that is the floor working as intended, not a signal to
    // start deleting. Including it here made the sweep fire on a store whose
    // retention was entirely within budget, which defeated the age grace above.
    if (kept + strayBytes > byteBudget) {
        for (const name of strays) {
            try {
                unlinkSync(join(dir, name));
            }
            catch { /* best effort */ }
        }
    }
}
