import { execFileSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmdirSync,
  statSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { jobTtlMs, maxRetainedJobBytes, maxRetainedJobs } from "./kiro.js";

/**
 * A job's metadata. Deliberately small and free of Kiro's transcript: listing
 * jobs parses every one of these, so a record that carried a multi-megabyte
 * body made `status` cost the size of the whole store. The transcript lives
 * beside it in `<id>.out` and is read only when someone asks for it.
 */
export interface Job {
  id: string;
  kind: string;
  status: "running" | "completed" | "failed" | "cancelled";
  startedAt: string;
  finishedAt?: string;
  pid?: number;
  /** Short inline explanation -- a synthesized failure reason, say. */
  note?: string;
  /** Byte length of `<id>.out`, when one was written. */
  resultBytes?: number;
}

export function getJobsDir(): string {
  if (process.env.KIRO_PLUGIN_JOBS_DIR) return process.env.KIRO_PLUGIN_JOBS_DIR;
  const uid = process.getuid?.();
  const suffix = uid === undefined ? (process.env.USERNAME || "user") : String(uid);
  return join(tmpdir(), `kiro-plugin-cc-jobs-${suffix}`);
}

/**
 * Job records hold Kiro's full output, which for a private repository is source
 * code and review commentary. The directory is therefore per-user and 0700 --
 * never the shared, world-readable default that `mkdir` would produce.
 */
export function ensureJobsDir(): string {
  const dir = getJobsDir();
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const uid = process.getuid?.();
  // Ownership and mode are only enforced for the directory the plugin picks
  // itself. An operator who points KIRO_PLUGIN_JOBS_DIR at a directory of
  // their own has already made that call, and silently chmod-ing a shared
  // directory out from under them would be worse than honouring it. Records
  // are written 0600 either way.
  if (uid !== undefined && !process.env.KIRO_PLUGIN_JOBS_DIR) {
    // lstat first: statSync would follow a symlink planted in the shared temp
    // path, so the uid check would pass while every record landed elsewhere.
    if (lstatSync(dir).isSymbolicLink()) {
      throw new Error(`jobs directory ${dir} is a symbolic link; refusing to use it`);
    }
    const st = statSync(dir);
    // A pre-created directory in the shared temp path would leak every result.
    if (st.uid !== uid) {
      throw new Error(`jobs directory ${dir} is owned by another user (uid ${st.uid}); refusing to use it`);
    }
    // `mkdir -p` leaves the mode of an existing directory alone.
    if ((st.mode & 0o077) !== 0) chmodSync(dir, 0o700);
  }
  return dir;
}

/**
 * Ids are generated by this plugin, but they arrive back from slash-command
 * arguments, so they are a trust boundary: without this, `result ../secret`
 * reads any file the user can.
 */
const JOB_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/;

export function isValidJobId(id: string): boolean {
  return JOB_ID_RE.test(id) && !id.includes("..");
}

const META_EXT = ".json";
const OUT_EXT = ".out";
const TMP_PREFIX = ".tmp-";

/**
 * The shape genId() produces. Pruning deletes files, so it only ever touches
 * names this plugin could itself have written -- an operator who points
 * KIRO_PLUGIN_JOBS_DIR at a directory of their own must not lose anything in
 * it. `isValidJobId` is far too permissive for that: it accepts "package",
 * which is how a stray package.json came to be deleted.
 */
const GENERATED_ID_RE = /^kiro-[0-9a-z]+-[0-9a-z]+$/;
const TMP_RE = /^\.tmp-\d+-\d+\.tmp$/;

function requireId(id: string): void {
  if (!isValidJobId(id)) throw new Error(`invalid job id: ${id}`);
}

// ensureJobsDir, not getJobsDir: reads have to clear the symlink and ownership
// guards too, or a planted directory is still readable by id.
function metaPath(id: string): string {
  requireId(id);
  return join(ensureJobsDir(), `${id}${META_EXT}`);
}

function outPath(id: string): string {
  requireId(id);
  return join(ensureJobsDir(), `${id}${OUT_EXT}`);
}

let tmpSeq = 0;
function nextTmpSeq(): number {
  tmpSeq += 1;
  return tmpSeq;
}

/** Write-then-rename, so a reader never observes a half-written file. */
function writeAtomic(target: string, data: string): void {
  const dir = ensureJobsDir();
  // Matched by TMP_RE, so an abandoned one is recognisably ours to clean up.
  // The counter, not just the path length, is what keeps two writes from the
  // same process apart -- they only happen to be sequential today.
  const tmp = join(dir, `${TMP_PREFIX}${process.pid}-${nextTmpSeq()}.tmp`);
  try {
    writeFileSync(tmp, data, { mode: 0o600 });
    renameSync(tmp, target);
  } catch (e) {
    try { if (existsSync(tmp)) unlinkSync(tmp); } catch { /* best effort */ }
    throw e;
  }
}

export function saveJob(job: Job): void {
  writeAtomic(metaPath(job.id), JSON.stringify(job, null, 2));
}

/** Stores a job's transcript and returns its byte length. */
export function saveJobResult(id: string, text: string): number {
  writeAtomic(outPath(id), text);
  return Buffer.byteLength(text);
}

export function readJobResult(id: string): string | null {
  if (!isValidJobId(id)) return null;
  try {
    return readFileSync(outPath(id), "utf-8");
  } catch {
    /* no transcript file -- may predate the split */
  }
  // Pre-split records hold the transcript inside the metadata. Without this the
  // commands reported "No result stored." with the body sitting right there.
  try {
    const parsed = JSON.parse(readFileSync(metaPath(id), "utf-8")) as { id?: unknown; result?: unknown };
    if (parsed && parsed.id === id && typeof parsed.result === "string") return parsed.result;
  } catch {
    /* unreadable or not in that shape */
  }
  return null;
}

/**
 * Returns null for anything that is not a readable, well-formed record for
 * `expectedId`. The id has to match the file it came from: saveJob always
 * writes `<id>.json`, so a record naming something else could never be updated
 * through its own id -- it would read as running forever while a second,
 * cancelled record accumulated alongside it.
 */
function readJobFile(path: string, expectedId: string): Job | null {
  let raw: string;
  try {
    raw = readFileSync(path, "utf-8");
  } catch {
    return null;
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  const job = parsed as Partial<Job>;
  if (typeof job.id !== "string" || typeof job.kind !== "string" || typeof job.startedAt !== "string") return null;
  if (job.id !== expectedId) return null;
  if (job.status !== "running" && job.status !== "completed" && job.status !== "failed" && job.status !== "cancelled") {
    return null;
  }
  // startedAt drives both sorting and the launch-window check, so a value that
  // does not parse makes the record unusable rather than merely odd.
  if (!Number.isFinite(Date.parse(job.startedAt))) return null;
  // finishedAt decides the TTL sweep: an unparseable value compares NaN, which
  // is false either way, and made the record permanently immune to pruning.
  if (job.finishedAt !== undefined) {
    if (typeof job.finishedAt !== "string" || !Number.isFinite(Date.parse(job.finishedAt))) return null;
  }
  // resultBytes is summed against the byte budget. A string would concatenate
  // instead of adding, inflating the accumulator and pruning transcripts that
  // are well inside it.
  if (job.resultBytes !== undefined) {
    if (typeof job.resultBytes !== "number" || !Number.isFinite(job.resultBytes) || job.resultBytes < 0) return null;
  }
  if (job.pid !== undefined && (typeof job.pid !== "number" || !Number.isInteger(job.pid))) return null;
  if (job.note !== undefined && typeof job.note !== "string") return null;
  return migrateInlineResult(job as Job & { result?: unknown });
}

/**
 * Records written before the metadata/transcript split carried the whole
 * transcript inline. Left as-is, `status` would parse and re-emit megabytes --
 * exactly the cost the split removed -- and the pruning byte budget would count
 * them as nothing, since it reads resultBytes. The field is dropped here and
 * its size accounted for; readJobResult still finds the body itself.
 */
function migrateInlineResult(job: Job & { result?: unknown }): Job {
  if (typeof job.result !== "string") {
    if ("result" in job) delete job.result;
    return job;
  }
  const bytes = Buffer.byteLength(job.result);
  delete job.result;
  return { ...job, resultBytes: job.resultBytes ?? bytes };
}

export function isPidAlive(pid: number): boolean {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (e) {
    // EPERM means the process exists but belongs to another user.
    return (e as NodeJS.ErrnoException).code === "EPERM";
  }
}

/**
 * Best-effort command line for `pid`, or null when it cannot be determined.
 * Used to confirm a recorded pid is still our runner and not a recycled one
 * before any signal is sent.
 */
export function pidCommandLine(pid: number): string | null {
  if (!Number.isInteger(pid) || pid <= 0) return null;
  try {
    return readFileSync(`/proc/${pid}/cmdline`, "utf-8").split("\0").filter(Boolean).join(" ");
  } catch {
    /* not Linux, or the process is gone */
  }
  try {
    // -ww: BSD and macOS truncate to the terminal width when stdout is not a
    // tty, which would drop the job id and defeat the check below.
    return execFileSync("ps", ["-ww", "-o", "args=", "-p", String(pid)], {
      encoding: "utf-8",
      timeout: 5_000,
      // Without this the timeout only sends SIGTERM and then keeps waiting.
      killSignal: "SIGKILL",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

/**
 * Whether `pid` is the runner this job started. A live pid proves nothing on
 * its own: pids are reused, and a record that outlives a reboot will routinely
 * point at somebody else's process. A command line that cannot be read at all
 * is treated as a match, because refusing on that basis would report every
 * healthy job as failed on a platform without /proc or ps.
 */
export function isOurRunner(pid: number, jobId: string): boolean {
  const cmd = pidCommandLine(pid);
  if (cmd === null) return true;
  return cmd.includes("kiro-runner") && cmd.includes(jobId);
}

/** How long a record may claim "running" without ever having recorded a pid. */
const PIDLESS_GRACE_MS = 60_000;

/**
 * A job is marked completed by the detached runner itself. If the runner was
 * killed before it could do that, the record would claim "running" forever, so
 * report the truth on read instead. This is read-side only -- nothing is
 * rewritten, because the runner may still be the one holding the pid.
 */
export function reconcile(job: Job): Job {
  if (job.status !== "running") return job;
  if (job.pid === undefined) {
    // The launcher writes the record before it knows the runner's pid, so there
    // is nothing to check liveness against in that window. A record that never
    // gained a pid means the launcher died in it.
    const age = Date.now() - Date.parse(job.startedAt);
    // Fail closed: an unusable timestamp must not keep a job "running" forever.
    if (Number.isFinite(age) && age <= PIDLESS_GRACE_MS) return job;
    // finishedAt is deliberately left as stored -- usually absent. Synthesizing
    // "now" made one stale record look like the most recently finished job on
    // every read, shadowing every genuine result for the whole retention window.
    return {
      ...job,
      status: "failed",
      note: job.note ?? "ERROR: the job was never started (its launcher exited before recording a runner).",
    };
  }
  if (isPidAlive(job.pid) && isOurRunner(job.pid, job.id)) return job;
  // As above: no invented finishedAt.
  return {
    ...job,
    status: "failed",
    note: job.note ?? "ERROR: the Kiro runner exited without recording a result (killed or crashed).",
  };
}

/** The record exactly as stored, with no liveness interpretation applied. */
export function loadJobRaw(id: string): Job | null {
  if (!isValidJobId(id)) return null;
  return readJobFile(metaPath(id), id);
}

export function loadJob(id: string): Job | null {
  const job = loadJobRaw(id);
  return job ? reconcile(job) : null;
}

export function listJobs(): Job[] {
  const dir = ensureJobsDir();
  const jobs: Job[] = [];
  for (const f of readdirSync(dir)) {
    if (!f.endsWith(META_EXT)) continue;
    const job = readJobFile(join(dir, f), f.slice(0, -META_EXT.length));
    if (job) jobs.push(reconcile(job));
  }
  return jobs.sort((a, b) => b.startedAt.localeCompare(a.startedAt));
}

function removeJobFiles(dir: string, id: string): void {
  for (const ext of [META_EXT, OUT_EXT]) {
    try {
      unlinkSync(join(dir, `${id}${ext}`));
    } catch {
      /* already gone, or never written */
    }
  }
}

function ageOf(dir: string, name: string): number {
  try {
    return Date.now() - statSync(join(dir, name)).mtimeMs;
  } catch {
    return 0;
  }
}

/**
 * Keeps the store bounded. Every run -- foreground included -- leaves a record
 * and a transcript, so without this the directory grows without limit. Three
 * budgets apply to finished jobs: age, count and total transcript bytes. A
 * running job is never touched.
 *
 * The scan is over the directory rather than over listJobs(), so that a record
 * listJobs rejects (corrupt, mismatched id, unusable timestamp), an orphaned
 * transcript and an abandoned temporary file are cleaned up too -- none of them
 * is visible to it. Only names this plugin could have generated are ever
 * removed, and only once past the TTL; everything else in the directory is left
 * strictly alone. Best effort throughout -- housekeeping must not be able to
 * fail a job.
 */
/**
 * The default jobs directory gained a per-user suffix, which left any
 * pre-upgrade store behind at the old shared path -- still holding transcripts,
 * and created with the default mode, so world-readable. Nothing reads it any
 * more, so tighten it, let its contents age out under the same rules as the
 * current store, and remove it once empty. Only files this plugin could have
 * generated are touched, and only ones we own.
 */
function drainLegacyJobsDir(): void {
  if (process.env.KIRO_PLUGIN_JOBS_DIR) return;
  const uid = process.getuid?.();
  if (uid === undefined) return;
  const legacy = join(tmpdir(), "kiro-plugin-cc-jobs");
  try {
    if (lstatSync(legacy).isSymbolicLink()) return;
    const st = statSync(legacy);
    if (!st.isDirectory() || st.uid !== uid) return;
    if ((st.mode & 0o077) !== 0) chmodSync(legacy, 0o700);
  } catch {
    return; // not there, or not ours to touch
  }

  const ttl = jobTtlMs();
  let names: string[];
  try {
    names = readdirSync(legacy);
  } catch {
    return;
  }
  for (const name of names) {
    const isOurs =
      TMP_RE.test(name) ||
      (name.endsWith(META_EXT) && GENERATED_ID_RE.test(name.slice(0, -META_EXT.length))) ||
      (name.endsWith(OUT_EXT) && GENERATED_ID_RE.test(name.slice(0, -OUT_EXT.length)));
    if (!isOurs) continue;
    if (ageOf(legacy, name) <= ttl) continue;
    try { unlinkSync(join(legacy, name)); } catch { /* best effort */ }
  }
  try {
    if (readdirSync(legacy).length === 0) rmdirSync(legacy);
  } catch {
    /* still has files, or gone already */
  }
}

export function pruneJobs(): void {
  drainLegacyJobsDir();
  let dir: string;
  let names: string[];
  try {
    dir = ensureJobsDir();
    names = readdirSync(dir);
  } catch {
    return;
  }

  const ttl = jobTtlMs();
  const live = new Set<string>();
  const terminal: Job[] = [];
  const transcripts: string[] = [];

  for (const name of names) {
    if (TMP_RE.test(name)) {
      // An abandoned write of ours. Nothing reads these, so age alone decides.
      if (ageOf(dir, name) > ttl) {
        try { unlinkSync(join(dir, name)); } catch { /* best effort */ }
      }
      continue;
    }
    if (name.endsWith(OUT_EXT)) {
      const id = name.slice(0, -OUT_EXT.length);
      if (GENERATED_ID_RE.test(id)) transcripts.push(id);
      continue;
    }
    if (!name.endsWith(META_EXT)) continue;
    const id = name.slice(0, -META_EXT.length);
    if (!GENERATED_ID_RE.test(id)) continue;
    const job = readJobFile(join(dir, name), id);
    if (!job) {
      // Ours by name but unreadable by every other code path, so it can only
      // ever take up space.
      if (ageOf(dir, name) > ttl) removeJobFiles(dir, id);
      continue;
    }
    if (reconcile(job).status === "running") live.add(id);
    else terminal.push(job);
  }

  terminal.sort((a, b) => b.startedAt.localeCompare(a.startedAt));

  const cutoff = Date.now() - ttl;
  const doomed = new Set<string>();
  for (const job of terminal) {
    if (Date.parse(job.finishedAt ?? job.startedAt) < cutoff) doomed.add(job.id);
  }
  // Newest-first, so the tail is what falls outside the count cap.
  for (const job of terminal.slice(maxRetainedJobs())) doomed.add(job.id);

  // Then trim by stored bytes: fifty ten-megabyte transcripts are within the
  // count cap and still make the store unusable. Walking newest-first and
  // dooming once the budget is exceeded keeps the most recent runs.
  const byteBudget = maxRetainedJobBytes();
  let kept = 0;
  for (const job of terminal) {
    if (doomed.has(job.id)) continue;
    kept += job.resultBytes ?? 0;
    if (kept > byteBudget) doomed.add(job.id);
  }

  for (const id of doomed) removeJobFiles(dir, id);

  // A transcript whose record is gone is unreachable. Age-guarded like every
  // other stale-file path, so a young record that merely failed to parse this
  // time does not lose its output.
  const retained = new Set(terminal.filter((j) => !doomed.has(j.id)).map((j) => j.id));
  for (const id of transcripts) {
    if (live.has(id) || retained.has(id) || doomed.has(id)) continue;
    if (ageOf(dir, `${id}${OUT_EXT}`) > ttl) {
      try { unlinkSync(join(dir, `${id}${OUT_EXT}`)); } catch { /* best effort */ }
    }
  }
}
